import type { Mineral, MineralFamily } from "@/types";

/**
 * Mineral families for the Mineral Universe window.
 * Labels are intentionally English-default; localized labels live in /content.
 */
export const MINERAL_FAMILIES: MineralFamily[] = [
  {
    key: "base",
    label: "Base Metals",
    description: "Industrial backbone metals and polymetallic systems.",
    minerals: ["Copper", "Zinc", "Lead", "Nickel", "Tin"],
  },
  {
    key: "precious",
    label: "Precious Metals",
    description: "High-value financial and fault-controlled metals.",
    minerals: ["Gold", "Silver"],
  },
  {
    key: "battery",
    label: "Battery Metals",
    description: "Energy transition and storage chain metals.",
    minerals: ["Cobalt", "Lithium", "Nickel", "Manganese"],
  },
  {
    key: "rareEarth",
    label: "Rare Earth / Magnet Metals",
    description: "Permanent magnet and defense-linked indicators.",
    minerals: ["Neodymium", "NdPr", "REE indicators"],
  },
  {
    key: "moroccanStrategic",
    label: "Moroccan Strategic Minerals",
    description: "National value-chain and industrial minerals.",
    minerals: ["Phosphate rock", "Industrial minerals", "Iron indicators"],
  },
  {
    key: "technology",
    label: "Technology-Linked Minerals",
    description: "Hardware, electronics and AI infrastructure supply chain.",
    minerals: ["Tin", "Copper", "Silver", "REE", "Nickel", "Cobalt"],
  },
];

/**
 * Mineral catalogue used by the Mineral Universe + Market Value Board.
 * All market values are PLACEHOLDERS — never hardcoded live facts.
 * Replace `marketReference` / `lastChecked` via the price-source layer.
 */
export const MINERALS: Mineral[] = [
  {
    id: "copper",
    name: "Copper",
    symbol: "Cu",
    family: "base",
    unit: "USD/t",
    marketReference: "Dynamic benchmark",
    strategicUse: "EVs, grids, electrification, data centers",
    linkedLayers: ["Isseksi", "QASSAS", "Aguelmous"],
    evidenceStatus: "fieldLinked",
    governanceStatus: "evidenceLinked",
    lastChecked: "Date checked: pending",
  },
  {
    id: "gold",
    name: "Gold",
    symbol: "Au",
    family: "precious",
    unit: "USD/oz",
    marketReference: "Dynamic benchmark",
    strategicUse: "High-value target, fault systems, financial metal",
    linkedLayers: ["QASSAS", "Aguelmous"],
    evidenceStatus: "indicator",
    governanceStatus: "marketReference",
    lastChecked: "Date checked: pending",
  },
  {
    id: "silver",
    name: "Silver",
    symbol: "Ag",
    family: "precious",
    unit: "USD/oz",
    marketReference: "Dynamic benchmark",
    strategicUse: "Solar, electronics, high conductivity",
    linkedLayers: ["QASSAS", "Aguelmous"],
    evidenceStatus: "indicator",
    governanceStatus: "marketReference",
    lastChecked: "Date checked: pending",
  },
  {
    id: "zinc",
    name: "Zinc",
    symbol: "Zn",
    family: "base",
    unit: "USD/t",
    marketReference: "Dynamic benchmark",
    strategicUse: "Base metal systems, industrial alloys",
    linkedLayers: ["Isseksi", "QASSAS"],
    evidenceStatus: "indicator",
    governanceStatus: "marketReference",
    lastChecked: "Date checked: pending",
  },
  {
    id: "lead",
    name: "Lead",
    symbol: "Pb",
    family: "base",
    unit: "USD/t",
    marketReference: "Dynamic benchmark",
    strategicUse: "Polymetallic systems, industrial use",
    linkedLayers: ["QASSAS"],
    evidenceStatus: "indicator",
    governanceStatus: "marketReference",
    lastChecked: "Date checked: pending",
  },
  {
    id: "nickel",
    name: "Nickel",
    symbol: "Ni",
    family: "battery",
    unit: "USD/t",
    marketReference: "Dynamic benchmark",
    strategicUse: "Batteries, stainless steel, EV chain",
    linkedLayers: ["Isseksi", "QASSAS"],
    evidenceStatus: "indicator",
    governanceStatus: "marketReference",
    lastChecked: "Date checked: pending",
  },
  {
    id: "cobalt",
    name: "Cobalt",
    symbol: "Co",
    family: "battery",
    unit: "USD/t",
    marketReference: "Dynamic benchmark",
    strategicUse: "Batteries, EV supply chain",
    linkedLayers: ["QASSAS"],
    evidenceStatus: "indicator",
    governanceStatus: "marketReference",
    lastChecked: "Date checked: pending",
  },
  {
    id: "lithium-carbonate",
    name: "Lithium Carbonate",
    symbol: "Li₂CO₃",
    family: "battery",
    unit: "USD/t",
    marketReference: "Dynamic benchmark",
    strategicUse: "Energy storage, EV batteries",
    linkedLayers: ["QASSAS"],
    evidenceStatus: "sourceRequired",
    governanceStatus: "marketReference",
    lastChecked: "Date checked: pending",
  },
  {
    id: "tin",
    name: "Tin",
    symbol: "Sn",
    family: "technology",
    unit: "USD/t",
    marketReference: "Dynamic benchmark",
    strategicUse: "Electronics, solder, AI hardware supply chain",
    linkedLayers: ["QASSAS"],
    evidenceStatus: "indicator",
    governanceStatus: "marketReference",
    lastChecked: "Date checked: pending",
  },
  {
    id: "manganese",
    name: "Manganese",
    symbol: "Mn",
    family: "battery",
    unit: "USD/t or mtu",
    marketReference: "Dynamic benchmark",
    strategicUse: "Batteries, steel alloys",
    linkedLayers: ["QASSAS"],
    evidenceStatus: "indicator",
    governanceStatus: "marketReference",
    lastChecked: "Date checked: pending",
  },
  {
    id: "neodymium-ndpr",
    name: "Neodymium / NdPr",
    symbol: "Nd",
    family: "rareEarth",
    unit: "USD/kg",
    marketReference: "Dynamic benchmark",
    strategicUse: "Permanent magnets, EV motors, defense, robotics",
    linkedLayers: ["QASSAS"],
    evidenceStatus: "sourceRequired",
    governanceStatus: "marketReference",
    lastChecked: "Date checked: pending",
  },
  {
    id: "phosphate-rock",
    name: "Phosphate Rock",
    symbol: "P",
    family: "moroccanStrategic",
    unit: "USD/t",
    marketReference: "Dynamic benchmark",
    strategicUse: "Moroccan strategic mineral layer",
    linkedLayers: ["AKANIL"],
    evidenceStatus: "sourceRequired",
    governanceStatus: "marketReference",
    lastChecked: "Date checked: pending",
  },
  {
    id: "industrial-minerals",
    name: "Industrial Minerals",
    family: "moroccanStrategic",
    unit: "Case-dependent",
    marketReference: "API-ready",
    strategicUse: "Construction, processing, industrial feedstock",
    linkedLayers: ["AKANIL", "Isseksi"],
    evidenceStatus: "sourceRequired",
    governanceStatus: "marketReference",
    lastChecked: "Date checked: pending",
  },
];

export function getMineralsByFamily(familyKey: string): Mineral[] {
  return MINERALS.filter((m) => m.family === familyKey);
}
